<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-L36TRD7L" failures="0" tests="7" name="entertimrtrack.CreateCustomer" time="52.274" errors="1" timestamp="2022-06-30T07:01:48 IST" skipped="0">
  <testcase classname="entertimrtrack.CreateCustomer" name="closeConnection" time="6.594">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at utilities.BaseClass1.closeConnection(BaseClass1.java:136)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:351)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
    </error>
  </testcase> <!-- closeConnection -->
  <system-out/>
  <testcase classname="entertimrtrack.CreateCustomer" name="login_ActiTime" time="0.418"/>
  <system-out/>
  <testcase classname="entertimrtrack.CreateCustomer" name="createTasks" time="6.637"/>
  <system-out/>
  <testcase classname="entertimrtrack.CreateCustomer" name="createTasks" time="7.218"/>
  <system-out/>
  <testcase classname="entertimrtrack.CreateCustomer" name="createTasks" time="17.226"/>
  <system-out/>
  <testcase classname="entertimrtrack.CreateCustomer" name="createTasks" time="6.955"/>
  <system-out/>
  <testcase classname="entertimrtrack.CreateCustomer" name="createTasks" time="7.226"/>
  <system-out/>
</testsuite> <!-- entertimrtrack.CreateCustomer -->
